### ISSUE TITLE
Watch mode isn't working

### ISSUE THREAD

**Issue by Zardoz89** [gabrysbiz/lesscss-maven-plugin-examples#1]
I just try your updated version of the plugin with the hope of enable  .less files watching and avoid doing tricky stuff with less.js on our webs when they are on debug/develop mode. Using `mvn biz.gabrys.maven.plugins:lesscss-maven-plugin:compile -Dwatch=true` simply only does a recompile of the .CSS file and exit.

I put here a capture : 

```
luis.panadero@DIGIBISCOM B:/r/j/l/e/digiwebcommons (master)> mvn biz.gabrys.maven.plugins:lesscss-maven-plugin:compile -Dwatch=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Entorno com▒n : Web
[INFO]    task-segment: [biz.gabrys.maven.plugins:lesscss-maven-plugin:compile]
[INFO] ------------------------------------------------------------------------
[INFO] [lesscss:compile {execution: default-cli}]
[INFO] Compiling 8 source files to B:\repos\java\librerias\entornocomun\digiwebcommons\target\digiwebcommons\css
[INFO] Finished source files compilation in 9.821 seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10 seconds
[INFO] Finished at: Fri Jan 29 09:41:16 CET 2016
[INFO] Final Memory: 20M/720M
[INFO] ------------------------------------------------------------------------
```

I try using  -Dforce=false and -DwatchInterval=2 with the same results.
I put here a copty of my maven 2 configuration for the plug-in :

```
      <plugin>
        <groupId>biz.gabrys.maven.plugins</groupId>
        <artifactId>lesscss-maven-plugin</artifactId>
        <version>1.1</version>
        <configuration>
          <sourceDirectory>${project.build.directory}/${project.artifactId}/less</sourceDirectory>
          <outputDirectory>${project.build.directory}/${project.artifactId}/css</outputDirectory>
          <compress>true</compress>
          <force>true</force>
          <encoding>UTF-8</encoding>
          <excludes>
            <exclude>comun/**/*.less</exclude>
            <exclude>**/*_comun.less</exclude>
            <exclude>**/*_.less</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>compile-less2</id>
            <phase>package</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

**NOTE**: We usually need to generate the final CSS on package phase, as we get other LESS and CSS files from other projects using war overlays. I we not do this, then the overlay overwrite our generated CSS files. I understand that this not should be related to the watch mode featur

**Comment by agabrys** [comment]
There is a bug in [Usage documentation](http://www.gabrys.biz/projects/lesscss-maven-plugin/RELEASE/usage.html#Invoke_from_the_command-line). You should set `-Dlesscss.watch=true` (when you execute `mvn` from command line, then use user properties names instead of XML elements names).

You don't need to set `force=false`, because it is always false when `watch=true` (see [compile goal documentation](http://www.gabrys.biz/projects/lesscss-maven-plugin/RELEASE/compile-mojo.html)).

**Comment by agabrys** [comment]
The bug in documentation has been fixed in version [1.2](http://www.gabrys.biz/projects/lesscss-maven-plugin/1.2-SNAPSHOT/usage.html#Invoke_from_the_command-line)

**Comment by agabrys** [comment]
Please let me know if you solve the problem.

**Comment by Zardoz89** [comment]
Actually I fallback to the old plugin :( I can't use a snapshot version of a plugin when we are generating war files to deploy on production....

**Comment by agabrys** [comment]
You can use 1.1 version. This bug is related with documentation, not code ;)

**Comment by agabrys** [comment]
I hope that you check 1.1 version and it works correctly.
I will close this issue. If you still have problems, then please reopen it.

**Comment by Zardoz89** [comment]
We finally are using your plugin, on the same way that the old plugin.
